sudo: false
language: node_js
node_js: 14
branches:
    only:
        - master
install:
    - npm install
before_script:
    - npm run build
script:
    - npm run test
after_success:
    - npm run coverall
