import Factory from '../Base/factory';
import WidgetTask from '../Widget/task';
export default class Current extends Factory<Current> {
    rulerContainerId: string;
    xRoomL2: number;
    xRoomR1: number;
    yRoom: number;
    autoAlignGuide: boolean;
    currentEventDisabled: boolean;
    sceneAnimate: string;
    contentMove: boolean;
    widgetMove: boolean;
    fullscreen: boolean;
    zoom: number;
    zoomStep: number;
    offsetX: number;
    offsetY: number;
    widget: WidgetTask | null;
    currentWidgetList: string[];
    currentSceneIndex: number | string;
    currentCreateSceneList: Array<number | string>;
    constructor(obj: any);
    clear(): void;
    taggerXRoomL2(): void;
    taggerXRoomR1(): void;
    zoomIn(step?: number): void;
    zoomOut(step?: number): void;
    resetZoom({ screenWidth, screenHeight }?: any): void;
    selectWidget(widget: WidgetTask): void;
    unSelectWidget(): void;
    unSelectWidgetList(): void;
    selectSceneIndex(val: number | string): void;
    openScene(id: number | string, animate?: string): void;
    closeScene(id: string): void;
}
